export const projects = [
    {
        id: "treering-ai-layout",
        title: "AI Driven Photobook Design System for TreeRing",
        description:
            "Led the design of an AI-powered photobook system that automated layout generation, reduced blank-canvas friction, and helped users create polished yearbook pages faster.",
        metric: "Reduced page-building time by 60%",
        tags: ["AI", "Generative AI", "Product Strategy"],
        image: "https://raw.githubusercontent.com/mchaplinsky/marissa-portfolio-ai/main/project_images/treering_ai_layout_system.jpeg",
        url: "https://marissachaplinsky123.framer.website/ai-driven-photobook-design-system-for-treering",
        keywords: [
            "ai",
            "artificial intelligence",
            "generative ai",
            "automation",
            "layout",
            "layout generation",
            "yearbook",
            "photobook",
            "treering",
            "tree ring",
            "creative tools",
            "product strategy",
            "ai system",
            "design system",
            "intelligent workflows",
            "responsive pages",
        ],
    },
    {
        id: "ai-portfolio-assistant",
        title: "AI Powered Portfolio Assistant",
        description:
            "Designed an AI assistant that helps recruiters and hiring managers explore Marissa’s experience, projects, and design philosophy through natural language questions.",
        metric: "Reduces recruiter search time across portfolio content",
        tags: ["AI", "Conversational UX", "Product Strategy"],
        image: "https://raw.githubusercontent.com/mchaplinsky/marissa-portfolio-ai/main/project_images/treering_ai_assistant.jpeg",
        url: "https://www.marissachaplinsky.com/blank-1",
        keywords: [
            "ai",
            "assistant",
            "chat",
            "chatbot",
            "agentic",
            "llm",
            "conversational ux",
            "ux ai",
            "product strategy",
            "portfolio ai",
            "intelligent interface",
            "recruiter experience",
            "question answering",
            "hiring manager",
        ],
    },
    {
        id: "healthcare-portal",
        title: "Healthcare Patient Portal Redesign",
        description:
            "Redesigned a healthcare patient portal to improve usability, accessibility, navigation, and digital engagement across complex patient workflows.",
        metric: "Increased patient engagement by 38%",
        tags: ["Healthcare", "Accessibility", "Service Design"],
        image: "https://raw.githubusercontent.com/mchaplinsky/marissa-portfolio-ai/main/project_images/lrbc_physician_platform.jpeg",
        url: "https://www.marissachaplinsky.com/healthcare-portal",
        keywords: [
            "healthcare",
            "patient",
            "portal",
            "medical",
            "hospital",
            "accessibility",
            "service design",
            "patient experience",
            "health system",
            "case management",
            "clinical",
            "digital health",
            "health ux",
            "provider",
        ],
    },
    {
        id: "mental-health-platform",
        title: "Mental Health Resource Platform",
        description:
            "Conducted UX research and redesigned digital mental health resources to improve discoverability, usability, clarity, and accessibility.",
        metric: "Improved access to mental health information",
        tags: ["Healthcare", "UX Research", "Accessibility"],
        image: "https://raw.githubusercontent.com/mchaplinsky/marissa-portfolio-ai/main/project_images/cmha_iras_platform.jpeg",
        url: "https://www.marissachaplinsky.com/cmha-project",
        keywords: [
            "mental health",
            "healthcare",
            "research",
            "ux research",
            "user research",
            "accessibility",
            "resource platform",
            "information design",
            "health services",
            "cmha",
            "content strategy",
            "discoverability",
            "public resources",
        ],
    },
    {
        id: "ab-testing-platform",
        title: "Experimentation and A/B Testing Platform",
        description:
            "Designed a testing framework that helped teams experiment with product features, evaluate behavior, and make more data-informed product decisions.",
        metric: "Enabled data-driven product experimentation across teams",
        tags: ["Product Strategy", "Experimentation", "Analytics"],
        image: "https://raw.githubusercontent.com/mchaplinsky/marissa-portfolio-ai/main/project_images/spd_criminal_record_system.jpeg",
        url: "https://www.marissachaplinsky.com/blank-1-1-1-1",
        keywords: [
            "ab testing",
            "a/b testing",
            "experimentation",
            "product analytics",
            "optimization",
            "conversion",
            "growth",
            "metrics",
            "product strategy",
            "data",
            "testing",
            "experiment design",
            "analytics",
        ],
    },
    {
        id: "government-service-portal",
        title: "Government Service Portal Redesign",
        description:
            "Redesigned a large-scale government service portal to improve navigation, workflows, document discovery, and overall service usability.",
        metric: "Reduced support requests by simplifying service workflows",
        tags: ["Enterprise UX", "Service Design", "Information Architecture"],
        image: "https://raw.githubusercontent.com/mchaplinsky/marissa-portfolio-ai/main/project_images/wcb_platform_redesign.jpeg",
        url: "https://www.marissachaplinsky.com/government-project",
        keywords: [
            "government",
            "public services",
            "enterprise",
            "workflow",
            "service design",
            "information architecture",
            "case management",
            "documentation",
            "process",
            "portal",
            "forms",
            "enterprise ux",
            "ia",
            "public sector",
        ],
    },
    {
        id: "design-systems-enterprise-workflows",
        title: "Enterprise Workflow and Systems Design",
        description:
            "Designed complex workflows, dashboards, and scalable product experiences across enterprise and service environments.",
        metric: "Improved clarity across multi-step workflows and internal systems",
        tags: ["Systems Thinking", "Enterprise UX", "Workflow Design"],
        image: "https://raw.githubusercontent.com/mchaplinsky/marissa-portfolio-ai/main/project_images/dmf_data_mapping_framework.jpeg",
        url: "https://www.marissachaplinsky.com/enterprise-workflows",
        keywords: [
            "systems thinking",
            "workflow",
            "enterprise",
            "dashboard",
            "internal tools",
            "b2b",
            "service flows",
            "complex systems",
            "process design",
            "operations",
            "product design",
            "multi-step flow",
        ],
    },
    {
        id: "camp-courthouse-wayfinding",
        title: "Camp Courthouse Wayfinding",
        description:
            "Designed a digital wayfinding experience that helped users navigate a complex courthouse environment more clearly and efficiently.",
        metric: "Improved navigation clarity across a complex public environment",
        tags: ["Government", "Service Design", "Wayfinding"],
        image: "https://raw.githubusercontent.com/mchaplinsky/marissa-portfolio-ai/main/project_images/camp_courthouse_wayfinding.jpeg",
        url: "https://www.marissachaplinsky.com",
        keywords: [
            "courthouse",
            "wayfinding",
            "navigation",
            "government",
            "public sector",
            "service design",
            "information design",
            "spatial navigation",
            "public services",
        ],
    },
    {
        id: "cdhbc-regulatory-portal",
        title: "CDHBC Regulatory Portal",
        description:
            "Designed a regulatory portal experience that improved access to complex information, workflows, and compliance-related content.",
        metric: "Simplified complex regulatory information and workflows",
        tags: ["Healthcare", "Enterprise UX", "Information Architecture"],
        image: "https://raw.githubusercontent.com/mchaplinsky/marissa-portfolio-ai/main/project_images/cdhbc_regulatory_portal.jpeg",
        url: "https://www.marissachaplinsky.com",
        keywords: [
            "cdhbc",
            "regulatory",
            "portal",
            "healthcare",
            "compliance",
            "information architecture",
            "enterprise ux",
            "complex systems",
            "content structure",
        ],
    },
    {
        id: "cmha-iras-platform",
        title: "CMHA Independent Rights Advice Platform",
        description:
            "Designed a digital platform that made mental health rights information more accessible, understandable, and actionable for users.",
        metric: "Improved access to rights information and service clarity",
        tags: ["Healthcare", "Accessibility", "Service Design"],
        image: "https://raw.githubusercontent.com/mchaplinsky/marissa-portfolio-ai/main/project_images/cmha_iras_platform.jpeg",
        url: "https://www.marissachaplinsky.com",
        keywords: [
            "cmha",
            "iras",
            "independent rights advice",
            "mental health",
            "healthcare",
            "accessibility",
            "service design",
            "public information",
            "rights information",
        ],
    },
    {
        id: "cmha-platform-redesign",
        title: "CMHA Platform Redesign",
        description:
            "Conducted research and redesign work to improve the structure, usability, accessibility, and clarity of a mental health support platform.",
        metric: "Improved discoverability and usability across mental health resources",
        tags: ["Healthcare", "UX Research", "Content Strategy"],
        image: "https://raw.githubusercontent.com/mchaplinsky/marissa-portfolio-ai/main/project_images/cmha_iras_platform.jpeg",
        url: "https://www.marissachaplinsky.com",
        keywords: [
            "cmha",
            "mental health",
            "healthcare",
            "ux research",
            "content strategy",
            "platform redesign",
            "discoverability",
            "accessibility",
            "resource design",
        ],
    },
    {
        id: "dmf-data-mapping-framework",
        title: "DMF Data Mapping Framework",
        description:
            "Created a data mapping framework that improved clarity, structure, and decision-making across complex information systems.",
        metric: "Improved visibility across complex system relationships",
        tags: ["Systems Thinking", "Information Architecture", "Enterprise UX"],
        image: "https://raw.githubusercontent.com/mchaplinsky/marissa-portfolio-ai/main/project_images/dmf_data_mapping_framework.jpeg",
        url: "https://www.marissachaplinsky.com",
        keywords: [
            "dmf",
            "data mapping",
            "framework",
            "systems thinking",
            "information architecture",
            "enterprise ux",
            "data relationships",
            "complex systems",
        ],
    },
    {
        id: "embc-emergency-management-portal",
        title: "EMBC Emergency Management Portal",
        description:
            "Designed a portal supporting emergency management workflows, coordination, and access to critical operational information.",
        metric: "Improved clarity and usability for emergency management workflows",
        tags: ["Government", "Enterprise UX", "Workflow Design"],
        image: "https://raw.githubusercontent.com/mchaplinsky/marissa-portfolio-ai/main/project_images/embc_emergency_management_portal.jpeg",
        url: "https://www.marissachaplinsky.com",
        keywords: [
            "embc",
            "emergency management",
            "government",
            "public sector",
            "workflow",
            "portal",
            "operations",
            "enterprise ux",
            "service coordination",
        ],
    },
    {
        id: "generative-ai-travel-photobook",
        title: "Generative AI Travel Photobook",
        description:
            "Explored how generative AI could automate storytelling, layout generation, and memory curation for travel photobooks.",
        metric: "Demonstrated AI-assisted storytelling and curation workflows",
        tags: ["AI", "Generative AI", "Creative Tools"],
        image: "https://raw.githubusercontent.com/mchaplinsky/marissa-portfolio-ai/main/project_images/treering_ai_layout_system.jpeg",
        url: "https://www.marissachaplinsky.com",
        keywords: [
            "generative ai",
            "ai",
            "travel photobook",
            "photobook",
            "storytelling",
            "creative tools",
            "automation",
            "layout generation",
            "memory curation",
        ],
    },
    {
        id: "lrbc-physician-platform",
        title: "LRBC Physician Platform",
        description:
            "Designed a physician-facing healthcare platform to improve workflows, clarity, and access to important information.",
        metric: "Improved task clarity and workflow usability for healthcare users",
        tags: ["Healthcare", "Enterprise UX", "Workflow Design"],
        image: "https://raw.githubusercontent.com/mchaplinsky/marissa-portfolio-ai/main/project_images/lrbc_physician_platform.jpeg",
        url: "https://www.marissachaplinsky.com",
        keywords: [
            "lrbc",
            "physician",
            "healthcare",
            "clinical",
            "workflow",
            "enterprise ux",
            "portal",
            "medical",
            "provider tools",
        ],
    },
    {
        id: "nccs-service-platform",
        title: "NCCS Service Platform",
        description:
            "Designed a service platform experience focused on clearer workflows, simplified access to information, and better coordination across services.",
        metric: "Simplified service workflows across a complex platform",
        tags: ["Service Design", "Enterprise UX", "Workflow Design"],
        image: "https://raw.githubusercontent.com/mchaplinsky/marissa-portfolio-ai/main/project_images/nccs_service_platform.jpeg",
        url: "https://www.marissachaplinsky.com",
        keywords: [
            "nccs",
            "service platform",
            "service design",
            "workflow",
            "enterprise ux",
            "coordination",
            "platform design",
            "complex systems",
        ],
    },
    {
        id: "spd-criminal-record-system",
        title: "SPD Criminal Record System",
        description:
            "Designed a public-facing digital service for criminal record workflows with a focus on clarity, trust, and task completion.",
        metric: "Improved clarity across a high-friction digital service flow",
        tags: ["Government", "Digital Service", "Workflow Design"],
        image: "https://raw.githubusercontent.com/mchaplinsky/marissa-portfolio-ai/main/project_images/spd_criminal_record_system.jpeg",
        url: "https://www.marissachaplinsky.com",
        keywords: [
            "spd",
            "criminal record",
            "government",
            "digital service",
            "workflow",
            "public sector",
            "forms",
            "task completion",
            "service design",
        ],
    },
    {
        id: "wcb-enterprise-information-architecture",
        title: "WCB Enterprise Information Architecture",
        description:
            "Led a structural redesign of enterprise information architecture to improve navigation clarity, content findability, and service pathways.",
        metric: "Improved discoverability across a complex service ecosystem",
        tags: ["Information Architecture", "Enterprise UX", "UX Strategy"],
        image: "https://raw.githubusercontent.com/mchaplinsky/marissa-portfolio-ai/main/project_images/wcb-enterprise-information-architecture.jpeg",
        url: "https://www.marissachaplinsky.com",
        keywords: [
            "wcb",
            "information architecture",
            "ia",
            "enterprise ux",
            "ux strategy",
            "service pathways",
            "content structure",
            "navigation",
            "findability",
        ],
    },
    {
        id: "wcb-platform-redesign",
        title: "WCB Platform Redesign",
        description:
            "Reframed a redesign request into a validated structural intervention, improving platform clarity through research, IA redesign, and prototype testing.",
        metric: "Reduced usability risk and improved navigation clarity",
        tags: ["Enterprise UX", "Information Architecture", "UX Research"],
        image: "https://raw.githubusercontent.com/mchaplinsky/marissa-portfolio-ai/main/project_images/wcb_platform_redesign.jpeg",
        url: "https://www.marissachaplinsky.com",
        keywords: [
            "wcb",
            "platform redesign",
            "enterprise",
            "information architecture",
            "ux research",
            "validation",
            "prototype testing",
            "service design",
            "government",
            "public sector",
        ],
    },
]
